"use strict";

module.exports = {
    CREATE_AUTHOR: 'CREATE_AUTHOR',
    CREATE_COURSE: 'CREATE_COURSE',
    INITIALIZE: 'INITIALIZE',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    DELETE_COURSE: 'DELETE_COURSE'
};